version: "3.9"

services: 
    api:
        container_name: media_api
        build:
            context: ./api
            dockerfile: Dockerfile
        volumes:
            - ./api:/app
        ports:
            - 8000:8000
    
    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
            PGADMIN_DEFAULT_PASSWORD: admin
        ports:
            - 8080:80
        

        


    