version: "3.9"

services: 
    api:
        container_name: media_api
        build:
            context: ./api
            dockerfile: Dockerfile
        ports:
            - 8000:8000

    db:
        image: postgres
        ports:
            - "5432:5432"
        env_file:
            - database.env # configure postgres
        volumes:
            - /Users/omarkhan/postgres_data:/var/lib/postgresql/data/
        


    